/// Plugin API list
///
/// This file is generated by shell script on 2021-11-02, please don't edit this file manually

class Methods {
  /// Load SVGA file from Flutter assets
  static const loadFromAsset = "loadFromAsset";
  
  /// Load SVGA file from remote url
  static const loadFromURL = "loadFromURL";
  
  /// Invoke when a SVGA widget is disposed
  static const releaseSVGAWidget = "releaseSVGAWidget";
  
  /// Pause SVGA widget animation to save resource
  static const pauseSVGAWidget = "pauseSVGAWidget";
  
  /// Resume a paused SVGA widget
  static const resumeSVGAWidget = "resumeSVGAWidget";
  
}