/// Plugin API list
///
/// This file is generated by shell script on 2021-11-02, please don't edit this file manually

package com.svga.plugin.svga_plugin.constants

class Methods {
    companion object {
        // Load SVGA file from Flutter assets
        const val loadFromAsset = "loadFromAsset"
        
        // Load SVGA file from remote url
        const val loadFromURL = "loadFromURL"
        
        // Invoke when a SVGA widget is disposed
        const val releaseSVGAWidget = "releaseSVGAWidget"
        
        // Pause SVGA widget animation to save resource
        const val pauseSVGAWidget = "pauseSVGAWidget"
        
        // Resume a paused SVGA widget
        const val resumeSVGAWidget = "resumeSVGAWidget"
        
    }
}