/// Status code list
///
/// This file is generated by shell script on 2021-11-02, please don't edit this file manually

package com.svga.plugin.svga_plugin.constants

enum class StatusCodes(val code: Int) {
    // Success
    OK(200),
    
    // Cannot parse PB data
    PB_PARSE_FAILED(100001),
    
    // Arguments from channel method params map with a wrong data type
    ARGUMENT_TYPE_ERROR(100002),
    
    // Error encountered during the texture creation process
    TEXTURE_ERROR(100003),
    
    // Some of the key params are missing
    DATA_MISSING(100004),
    
    // Data format or data content gets wrong
    DATA_ERROR(100005),
    
    // SVGA parser failed to handle the source
    SVGA_PARSE_ERROR(100006),
    
    // Plugin does not provide a legal widget id
    ILLEGAL_WIDGET_ID(100007),
    
}