/// Plugin API list
///
/// This file is generated by shell script on 2021-11-02, please don't edit this file manually

#import <Foundation/Foundation.h>

// Load SVGA file from Flutter assets
extern NSString *const loadFromAsset;

// Load SVGA file from remote url
extern NSString *const loadFromURL;

// Invoke when a SVGA widget is disposed
extern NSString *const releaseSVGAWidget;

// Pause SVGA widget animation to save resource
extern NSString *const pauseSVGAWidget;

// Resume a paused SVGA widget
extern NSString *const resumeSVGAWidget;

