/// Plugin API list
///
/// This file is generated by shell script on 2021-11-02, please don't edit this file manually

#import "Methods.h"

// Load SVGA file from Flutter assets
NSString *const loadFromAsset = @"loadFromAsset";

// Load SVGA file from remote url
NSString *const loadFromURL = @"loadFromURL";

// Invoke when a SVGA widget is disposed
NSString *const releaseSVGAWidget = @"releaseSVGAWidget";

// Pause SVGA widget animation to save resource
NSString *const pauseSVGAWidget = @"pauseSVGAWidget";

// Resume a paused SVGA widget
NSString *const resumeSVGAWidget = @"resumeSVGAWidget";

