/// Status code list
///
/// This file is generated by shell script on 2021-11-02, please don't edit this file manually

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, StatusCodes) {
    // Success
    ok = 200,
    
    // Cannot parse PB data
    pbParseFailed = 100001,
    
    // Arguments from channel method params map with a wrong data type
    argumentTypeError = 100002,
    
    // Error encountered during the texture creation process
    textureError = 100003,
    
    // Some of the key params are missing
    dataMissing = 100004,
    
    // Data format or data content gets wrong
    dataError = 100005,
    
    // SVGA parser failed to handle the source
    svgaParseError = 100006,
    
    // Plugin does not provide a legal widget id
    illegalWidgetId = 100007,
    
};